stages:
- lint
- test
- deploy
lint:
  stage: lint
  script:
  - echo "Linting project"
  - npm i
  - npm run check-dependencies
  - npm run lint
  tags:
  - ionic
test:
  stage: test
  script:
  - echo "Test"
  tags:
  - ionic
staging_android:
  stage: deploy
  script:
  - source $HOME/.profile
  - mkdir -p www
  - whoami
  - pwd
  - ls -la
  - ionic info
  - echo "--- Preparing Ionic app"
  - npm install
  - cordova prepare android
  - echo "--- Building Ionic app"
  - npm run build:android:staging:prod
  - echo "--- Upload to hockey"
  - "cd platforms/android/app/build/outputs/apk/debug/ && curl -F \"status=2\" -F \"notify=0\" -F \"notes=Continuous Integration Test\" -F \"notes_type=1\" -F \"ipa=@app-debug.apk\" -H \"X-HockeyAppToken: a23112aed3a84f85b85323240f88d480\" https://rink.hockeyapp.net/api/2/apps/5e01523916244d7cbd63c4f52e166d39/app_versions/upload"
  only:
  - tags
  tags:
  - ionic-android
staging_ios:
  stage: deploy
  script:
  - source $HOME/.profile
  - mkdir -p www
  - whoami
  - pwd
  - ls -la
  - ionic info
  - echo "--- Preparing Ionic app"
  - npm install
  - cordova prepare ios
  - echo "--- Building Ionic app"
  - npm run build:ios:staging:prod
  - ionic cordova build ios --c=staging-prod --release --buildConfig ./build.json --packageType="ad-hoc"
  - ls platforms/ios/build/device/
  - echo "Upload to hockey"
  - "cd platforms/ios/build/device/ && curl -F \"status=2\" -F \"notify=0\" -F \"notes=Continuous Integration Test\" -F \"notes_type=1\" -F \"ipa=@prototype.ipa\" -H \"X-HockeyAppToken: f438b3b2230949a086b0604dfd17ecbb\" https://rink.hockeyapp.net/api/2/apps/66f7adb447f5491ea249d1a998842ba7/app_versions/upload"
  only:
  - tags
  tags:
  - ionic-ios
release_android:
  stage: deploy
  script:
  - source $HOME/.profile
  - mkdir -p www
  - whoami
  - pwd
  - ls -la
  - ionic info
  - echo "--- Preparing Ionic app"
  - npm install
  - cordova prepare android
  - echo "--- Building Ionic app"
  - npm run build:android:release
  - echo "--- Release Signing"
  - cd platforms/android/app/build/outputs/apk/release/
  - echo $KEYSTORE_FILE | base64 -d > production.keystore
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore production.keystore -storepass $KEYSTORE_PASSWORD app-release-unsigned.apk $KEY_ALIAS
  - $HOME/android-sdk/build-tools/28.0.3/zipalign -v 4 app-release-unsigned.apk AppName.apk
  only:
  - tags
  when: manual
  tags:
  - ionic-android
  artifacts:
    paths:
    - platforms/android/app/build/outputs/apk/release
